package com.example.chat

import java.util.Locale

enum class AppLanguage {
    EN,
    ZH;

    companion object {
        fun fromStored(value: String?): AppLanguage =
            when (value?.uppercase(Locale.ROOT)) {
                "ZH" -> ZH
                else -> EN
            }

        fun systemDefault(): AppLanguage =
            if (Locale.getDefault().language.startsWith("zh", ignoreCase = true)) ZH else EN
    }
}

enum class AppDisplayMode {
    SYSTEM,
    LIGHT,
    DARK;

    companion object {
        fun fromStored(value: String?): AppDisplayMode =
            when (value?.uppercase(Locale.ROOT)) {
                "LIGHT" -> LIGHT
                "DARK" -> DARK
                else -> SYSTEM
            }
    }
}

/**
 * User-chosen text size.
 *
 * The type ramp is already a little larger than stock Material 3 for this
 * audience, but "a little larger" is a guess about a family that spans several
 * generations. This lets each person settle it for themselves rather than the
 * app picking one compromise for a grandparent and a teenager at once.
 *
 * The factor scales the whole ramp, so the relationships between title, body and
 * label sizes are preserved at every setting.
 */
enum class AppTextSize(val scale: Float) {
    SMALL(0.92f),
    MEDIUM(1.0f),
    LARGE(1.14f);

    companion object {
        fun fromStored(value: String?): AppTextSize =
            when (value?.uppercase(Locale.ROOT)) {
                "SMALL" -> SMALL
                "LARGE" -> LARGE
                else -> MEDIUM
            }
    }
}

// Keep large string sections grouped: DEX method calls cannot exceed 255 argument registers.
data class AppAccessibilityStrings(
    val messageStatusSent: String,
    val messageStatusDelivered: String,
    val messageStatusRead: String,
    val expandedLabel: String,
    val collapsedLabel: String,
    val selectedLabel: String,
)

data class AppConversationPreferenceStrings(
    val muteConversation: String,
    val unmuteConversation: String,
    val conversationMuted: String,
    val conversationUnmuted: String,
    val textSize: String,
    val textSizeSmall: String,
    val textSizeMedium: String,
    val textSizeLarge: String,
)

data class AppCallStrings(
    val voiceCall: String,
    val incomingCall: String,
    val calling: String,
    val callConnecting: String,
    val callActive: String,
    val callEnded: String,
    val callRejected: String,
    val callBusy: String,
    val callUnavailable: String,
    val callReconnecting: String,
    val callConnectionLost: String,
    val callFailed: String,
    val accept: String,
    val decline: String,
    val endCall: String,
    val mute: String,
    val unmute: String,
    val audioOutput: String,
    val speaker: String,
    val earpiece: String,
    val bluetooth: String,
    val minimizeCall: String,
    val returnToCall: String,
    val overlayPermissionHint: String,
    val microphonePermissionDenied: String,
    val directCallOnly: String,
)

data class AppDateStrings(
    val today: String,
    val yesterday: String,
)

/**
 * About and troubleshooting.
 *
 * These were previously inline `if (language == ZH) "..." else "..."`
 * conditionals in SettingsAboutScreen, which put translations in a screen file
 * where nobody would look for them. Grouped rather than added as top-level
 * AppStrings parameters - see the DEX argument-register limit.
 */
data class AppMaintenanceStrings(
    val appVersion: String,
    val updatesSection: String,
    val troubleshootingSection: String,
    val installUpdateAction: String,
    val pushSelfTest: String,
    val pushSelfTestRunning: String,
    val pushSelfTestHint: String,
    val exportDiagnostics: String,
    val exportDiagnosticsHint: String,
    val profileSection: String,
    val dangerZoneSection: String,
    val changeAvatarHint: String,
    val changePasswordHint: String,
    val signOutHint: String,
    val deleteAccountHint: String,
    val deviceStatusPending: String,
    val deviceStatusTrusted: String,
    val thisDeviceSection: String,
    val deleteContactConfirm: String,
)

data class AppBlogStrings(
    val title: String,
    val chatsTab: String,
    val blogTab: String,
    val newPost: String,
    val composeHint: String,
    val addMedia: String,
    val publish: String,
    val publishing: String,
    val emptyTitle: String,
    val emptyBody: String,
    val like: String,
    val unlike: String,
    val comments: String,
    val writeComment: String,
    val sendComment: String,
    val deletePost: String,
    val deletePostConfirm: String,
    val deleteComment: String,
    val deleteCommentConfirm: String,
    val mediaLimit: String,
    val mediaOneVideoOnly: String,
    val mediaTruncated: String,
    val video: String,
    val announcement: String,
    val loadOlder: String,
    val notifications: String,
    val notificationsHint: String,
)

data class AppStrings(
    val familyChat: String,
    val appSubtitle: String,
    val serverUrl: String,
    val username: String,
    val password: String,
    val login: String,
    val register: String,
    val createAccount: String,
    val backToLogin: String,
    val confirmPassword: String,
    val registrationPending: String,
    val passwordTooShort: String,
    val passwordsDoNotMatch: String,
    val requestAlreadyPending: String,
    val unableToRegister: String,
    val connected: String,
    val disconnected: String,
    val reconnecting: String,
    val syncing: String,
    val e2ee: String,
    val settings: String,
    val general: String,
    val about: String,
    val security: String,
    val accountManage: String,
    val friendManage: String,
    val groupManage: String,
    val deleteHistory: String,
    val clearChatHistory: String,
    val deleteHistoryConfirm: String,
    val deleteDirectChat: String,
    val deleteDirectChatConfirm: String,
    val deleteContact: String,
    val deleteGroup: String,
    val deleteGroupConfirm: String,
    val leaveGroup: String,
    val leaveGroupConfirm: String,
    val requestAccountDeletion: String,
    val requestAccountDeletionConfirm: String,
    val accountDeletionRequested: String,
    val conversationDeleted: String,
    val groupDeleted: String,
    val ownerTransferred: String,
    val groupLeft: String,
    val unableToDeleteConversation: String,
    val unableToDeleteGroup: String,
    val unableToLeaveGroup: String,
    val ownerCannotLeaveGroup: String,
    val delete: String,
    val cancel: String,
    val changePassword: String,
    val changeUsername: String,
    val changeAvatar: String,
    val changeGroupIcon: String,
    val avatarHint: String,
    val avatarCropHint: String,
    val userId: String,
    val deviceSecurity: String,
    val safetyCode: String,
    val deviceId: String,
    val deviceName: String,
    val safetyCodeHint: String,
    val noDeviceIdentity: String,
    val devices: String,
    val currentDevice: String,
    val lastSeen: String,
    val removeDevice: String,
    val removeDeviceConfirm: String,
    val deviceAdded: String,
    val deviceRemoved: String,
    val groupKeyStatus: String,
    val groupKeyEpoch: String,
    val groupKeyDevicesReady: String,
    val peerSafetyCode: String,
    val safetyCodeChanged: String,
    val noPeerSafetyCode: String,
    val contactsAndGroups: String,
    val shareToChat: String,
    val shareLoginFirst: String,
    val sharedContentUnsupported: String,
    val noChatsTitle: String,
    val noChatsBody: String,
    val addContact: String,
    val joinGroup: String,
    val newGroup: String,
    val groupId: String,
    val groupName: String,
    val groupCode: String,
    val search: String,
    val approve: String,
    val reject: String,
    val owner: String,
    val member: String,
    val privateMessage: String,
    val removeMember: String,
    val removeMemberConfirm: String,
    val transferOwner: String,
    val transferOwnerConfirm: String,
    val addAdmin: String,
    val requestAdmin: String,
    val removeAdmin: String,
    val removeAdminConfirm: String,
    val adminRemoved: String,
    val addGroupMember: String,
    val selectContact: String,
    val selectMember: String,
    val noAvailableContacts: String,
    val noAvailableMembers: String,
    val memberAdded: String,
    val adminLimit: String,
    val messageExpiration: String,
    val noExpiration: String,
    val hours8: String,
    val hours24: String,
    val hours72: String,
    val incomingRequests: String,
    val outgoingRequests: String,
    val requestContact: String,
    val requestJoin: String,
    val contactRequestSent: String,
    val joinRequestSent: String,
    val contactApproved: String,
    val joinApproved: String,
    val requestRejected: String,
    val groupCreated: String,
    val alreadyConnected: String,
    val alreadyInGroup: String,
    val userNotFound: String,
    val groupNotFound: String,
    val invalidUserId: String,
    val invalidGroupId: String,
    val groupNameRequired: String,
    val incomingContactAlreadyPending: String,
    val notGroupAdmin: String,
    val notContact: String,
    val requestFailed: String,
    val newPassword: String,
    val newUsername: String,
    val usernameEmpty: String,
    val invalidUsername: String,
    val usernameTaken: String,
    val unableToChangeUsername: String,
    val save: String,
    val replyingTo: String,
    val typeMessage: String,
    val unreadMessages: String,
    val open: String,
    val downloadOpen: String,
    val encryptedMessage: String,
    val unableToDecrypt: String,
    val encryptedAttachment: String,
    val tapOpen: String,
    val image: String,
    val voiceNote: String,
    val file: String,
    val language: String,
    val displayMode: String,
    val followSystem: String,
    val lightMode: String,
    val darkMode: String,
    val systemColors: String,
    val systemColorsHint: String,
    val backAgainToExit: String,
    val logout: String,
    val refresh: String,
    val scrollToTop: String,
    val scrollToBottom: String,
    val admin: String,
    val statusSeparator: String,
    val showMenu: String,
    val hideMenu: String,
    val addMedia: String,
    val chooseAttachment: String,
    val takePhoto: String,
    val startVoice: String,
    val sendVoice: String,
    val sendMessage: String,
    val recording: String,
    val holdToTalk: String,
    val releaseToSend: String,
    val releaseToCancel: String,
    val keyboardInput: String,
    val play: String,
    val pause: String,
    val uploading: String,
    val downloading: String,
    val recalledMessage: String,
    val longPressRecall: String,
    val attachmentRemoved: String,
    val recallAction: String,
    val currentVersion: String,
    val latestVersion: String,
    val checkUpdate: String,
    val installUpdate: String,
    val latestVersionInstalled: String,
    val updateAvailable: String,
    val updatePromptTitle: String,
    val updatePromptBody: String,
    val updateNow: String,
    val later: String,
    val noReleaseUploaded: String,
    val checkingUpdate: String,
    val updateDownloaded: String,
    val downloadUpdate: String,
    val openInstaller: String,
    val prereleaseBuilds: String,
    val prereleaseCenter: String,
    val prereleaseAvailable: String,
    val noPrereleaseUploaded: String,
    val sendPhoto: String,
    val cameraPermissionDenied: String,
    val cameraUnavailable: String,
    val cameraCaptureFailed: String,
    val sendFailed: String,
    val retrySend: String,
    val retrySendConfirm: String,
    val accessibility: AppAccessibilityStrings,
    val conversationPreferences: AppConversationPreferenceStrings,
    val deleteLocalMessage: String,
    val call: AppCallStrings,
    val dates: AppDateStrings,
    val maintenance: AppMaintenanceStrings,
    val blog: AppBlogStrings,
) {
    val messageStatusSent get() = accessibility.messageStatusSent
    val messageStatusDelivered get() = accessibility.messageStatusDelivered
    val messageStatusRead get() = accessibility.messageStatusRead
    val expandedLabel get() = accessibility.expandedLabel
    val collapsedLabel get() = accessibility.collapsedLabel
    val selectedLabel get() = accessibility.selectedLabel

    val muteConversation get() = conversationPreferences.muteConversation
    val unmuteConversation get() = conversationPreferences.unmuteConversation
    val conversationMuted get() = conversationPreferences.conversationMuted
    val conversationUnmuted get() = conversationPreferences.conversationUnmuted
    val textSize get() = conversationPreferences.textSize
    val textSizeSmall get() = conversationPreferences.textSizeSmall
    val textSizeMedium get() = conversationPreferences.textSizeMedium
    val textSizeLarge get() = conversationPreferences.textSizeLarge

    val voiceCall get() = call.voiceCall
    val incomingCall get() = call.incomingCall
    val calling get() = call.calling
    val callConnecting get() = call.callConnecting
    val callActive get() = call.callActive
    val callEnded get() = call.callEnded
    val callRejected get() = call.callRejected
    val callBusy get() = call.callBusy
    val callUnavailable get() = call.callUnavailable
    val callReconnecting get() = call.callReconnecting
    val callConnectionLost get() = call.callConnectionLost
    val callFailed get() = call.callFailed
    val accept get() = call.accept
    val decline get() = call.decline
    val endCall get() = call.endCall
    val mute get() = call.mute
    val unmute get() = call.unmute
    val audioOutput get() = call.audioOutput
    val speaker get() = call.speaker
    val earpiece get() = call.earpiece
    val bluetooth get() = call.bluetooth
    val minimizeCall get() = call.minimizeCall
    val returnToCall get() = call.returnToCall
    val overlayPermissionHint get() = call.overlayPermissionHint
    val microphonePermissionDenied get() = call.microphonePermissionDenied
    val directCallOnly get() = call.directCallOnly

    val today get() = dates.today
    val yesterday get() = dates.yesterday

    val appVersion get() = maintenance.appVersion
    val updatesSection get() = maintenance.updatesSection
    val troubleshootingSection get() = maintenance.troubleshootingSection
    val installUpdateAction get() = maintenance.installUpdateAction
    val pushSelfTest get() = maintenance.pushSelfTest
    val pushSelfTestRunning get() = maintenance.pushSelfTestRunning
    val pushSelfTestHint get() = maintenance.pushSelfTestHint
    val exportDiagnostics get() = maintenance.exportDiagnostics
    val exportDiagnosticsHint get() = maintenance.exportDiagnosticsHint
    val profileSection get() = maintenance.profileSection
    val dangerZoneSection get() = maintenance.dangerZoneSection
    val changeAvatarHint get() = maintenance.changeAvatarHint
    val changePasswordHint get() = maintenance.changePasswordHint
    val signOutHint get() = maintenance.signOutHint
    val deleteAccountHint get() = maintenance.deleteAccountHint
    val deviceStatusPending get() = maintenance.deviceStatusPending
    val deviceStatusTrusted get() = maintenance.deviceStatusTrusted
    val thisDeviceSection get() = maintenance.thisDeviceSection
    val deleteContactConfirm get() = maintenance.deleteContactConfirm
}

fun stringsFor(language: AppLanguage): AppStrings =
    when (language) {
        AppLanguage.ZH -> AppStrings(
            familyChat = "\u5bb6\u5ead\u804a\u5929\u5ba4",
            appSubtitle = "\u652f\u6301\u52a0\u5bc6\u6d88\u606f\u7684 Android \u5ba2\u6237\u7aef",
            serverUrl = "\u670d\u52a1\u5668\u5730\u5740",
            username = "\u7528\u6237\u540d",
            password = "\u5bc6\u7801",
            login = "\u767b\u5f55",
            register = "\u6ce8\u518c",
            createAccount = "\u7533\u8bf7\u6ce8\u518c",
            backToLogin = "\u8fd4\u56de\u767b\u5f55",
            confirmPassword = "\u786e\u8ba4\u5bc6\u7801",
            registrationPending = "\u6ce8\u518c\u7533\u8bf7\u5df2\u63d0\u4ea4\uff0c\u8bf7\u7b49\u5f85\u7ba1\u7406\u5458\u6279\u51c6",
            passwordTooShort = "\u5bc6\u7801\u81f3\u5c11\u9700\u8981 8 \u4f4d",
            passwordsDoNotMatch = "\u4e24\u6b21\u8f93\u5165\u7684\u5bc6\u7801\u4e0d\u4e00\u81f4",
            requestAlreadyPending = "\u8fd9\u4e2a\u7528\u6237\u540d\u5df2\u6709\u5f85\u5ba1\u6279\u7533\u8bf7",
            unableToRegister = "\u65e0\u6cd5\u63d0\u4ea4\u6ce8\u518c\u7533\u8bf7",
            connected = "\u5df2\u8fde\u63a5",
            disconnected = "\u672a\u8fde\u63a5",
            reconnecting = "\u6b63\u5728\u91cd\u8fde",
            syncing = "\u540c\u6b65\u4e2d",
            e2ee = "\u7aef\u5230\u7aef\u52a0\u5bc6",
            settings = "\u8bbe\u7f6e",
            general = "\u901a\u7528",
            about = "\u5173\u4e8e",
            security = "\u5b89\u5168",
            accountManage = "\u8d26\u53f7\u7ba1\u7406",
            friendManage = "\u597d\u53cb\u7ba1\u7406",
            groupManage = "\u7fa4\u804a\u7ba1\u7406",
            deleteHistory = "\u6e05\u7a7a\u8bb0\u5f55",
            clearChatHistory = "\u6e05\u7a7a\u5f53\u524d\u804a\u5929\u8bb0\u5f55",
            deleteHistoryConfirm = "\u786e\u8ba4\u6e05\u7a7a\u6240\u6709\u4eba\u7684\u804a\u5929\u8bb0\u5f55\u5417\uff1f",
            deleteDirectChat = "删除单聊",
            deleteDirectChatConfirm = "确认删除这个单聊吗？聊天记录和附件也会一起删除，对方也会失去这个单聊。",
            deleteContact = "\u5220\u9664\u8054\u7cfb\u4eba",
            deleteGroup = "\u5220\u9664\u7fa4\u804a",
            deleteGroupConfirm = "\u786e\u8ba4\u5220\u9664\u8fd9\u4e2a\u7fa4\u804a\u5417\uff1f\u5220\u9664\u540e\u6240\u6709\u6210\u5458\u90fd\u4f1a\u5931\u53bb\u8fd9\u4e2a\u7fa4\u804a\u3002",
            leaveGroup = "退出群聊",
            leaveGroupConfirm = "确认退出这个群聊吗？退出不需要管理员批准。",
            requestAccountDeletion = "申请注销账号",
            requestAccountDeletionConfirm = "确认提交注销账号申请吗？管理员批准后账号将无法登录。",
            accountDeletionRequested = "注销账号申请已提交，请等待管理员批准",
            conversationDeleted = "单聊已删除",
            groupDeleted = "\u7fa4\u804a\u5df2\u5220\u9664",
            groupLeft = "已退出群聊",
            unableToDeleteConversation = "无法删除这个单聊",
            unableToDeleteGroup = "\u65e0\u6cd5\u5220\u9664\u8fd9\u4e2a\u7fa4\u804a",
            unableToLeaveGroup = "无法退出群聊",
            ownerCannotLeaveGroup = "\u521d\u59cb\u7ba1\u7406\u5458\u4e0d\u80fd\u76f4\u63a5\u9000\u7fa4\uff0c\u8bf7\u5148\u8f6c\u8ba9\u521d\u59cb\u7ba1\u7406\u5458\u6216\u5220\u9664\u7fa4\u804a",
            ownerTransferred = "\u521d\u59cb\u7ba1\u7406\u5458\u5df2\u8f6c\u8ba9",
            delete = "\u5220\u9664",
            cancel = "\u53d6\u6d88",
            changePassword = "\u4fee\u6539\u5bc6\u7801",
            changeUsername = "\u4fee\u6539\u7528\u6237\u540d",
            changeAvatar = "\u66f4\u6362\u5934\u50cf",
            changeGroupIcon = "\u66f4\u6539\u7fa4\u56fe\u6807",
            avatarHint = "\u4e0a\u4f20\u4e00\u5f20\u65b0\u5934\u50cf",
            avatarCropHint = "\u62d6\u52a8\u548c\u7f29\u653e\u56fe\u7247\uff0c\u8c03\u6574\u5706\u5f62\u88c1\u526a\u533a\u57df",
            userId = "ID",
            deviceSecurity = "\u8bbe\u5907\u5b89\u5168",
            safetyCode = "\u5b89\u5168\u7801",
            deviceId = "\u8bbe\u5907 ID",
            deviceName = "\u8bbe\u5907\u540d\u79f0",
            safetyCodeHint = "\u8fd9\u4e2a\u5b89\u5168\u7801\u6765\u81ea\u672c\u673a\u8eab\u4efd\u516c\u94a5\u3002\u6362\u624b\u673a\u6216\u91cd\u88c5 App \u540e\u4f1a\u53d8\u5316\u3002",
            noDeviceIdentity = "\u8bbe\u5907\u8eab\u4efd\u5c1a\u672a\u751f\u6210",
            devices = "\u5df2\u767b\u5f55\u8bbe\u5907",
            currentDevice = "\u5f53\u524d\u8bbe\u5907",
            lastSeen = "\u6700\u540e\u6d3b\u8dc3",
            removeDevice = "\u79fb\u9664\u8bbe\u5907",
            removeDeviceConfirm = "\u786e\u8ba4\u79fb\u9664\u8bbe\u5907 %s\uff1f\u8be5\u8bbe\u5907\u5c06\u65e0\u6cd5\u7ee7\u7eed\u89e3\u5bc6\u65b0\u7684\u7fa4\u804a\u5bc6\u94a5\u3002",
            deviceAdded = "\u6709\u65b0\u8bbe\u5907\u52a0\u5165\uff0c\u8bf7\u6838\u5bf9\u5b89\u5168\u7801",
            deviceRemoved = "\u8bbe\u5907\u5df2\u79fb\u9664\uff0c\u7fa4\u804a\u5bc6\u94a5\u5df2\u8f6e\u6362",
            groupKeyStatus = "\u7fa4\u804a\u5bc6\u94a5\u72b6\u6001",
            groupKeyEpoch = "\u5bc6\u94a5\u4e16\u4ee3",
            groupKeyDevicesReady = "\u5df2\u8986\u76d6\u8bbe\u5907",
            peerSafetyCode = "对方安全码",
            safetyCodeChanged = "\u5b89\u5168\u7801\u5df2\u53d8\u66f4\uff0c\u8bf7\u548c\u5bf9\u65b9\u786e\u8ba4\u8eab\u4efd",
            noPeerSafetyCode = "对方还没有上传设备安全码",
            contactsAndGroups = "联系人和群聊",
            shareToChat = "\u9009\u62e9\u804a\u5929\u53d1\u9001",
            shareLoginFirst = "\u8bf7\u5148\u767b\u5f55\u540e\u518d\u5206\u4eab",
            sharedContentUnsupported = "\u6682\u4e0d\u652f\u6301\u8fd9\u79cd\u5206\u4eab\u5185\u5bb9",
            noChatsTitle = "\u8fd8\u6ca1\u6709\u804a\u5929",
            noChatsBody = "\u6dfb\u52a0\u8054\u7cfb\u4eba\u6216\u52a0\u5165\u7fa4\u804a\u540e\uff0c\u5c31\u4f1a\u663e\u793a\u5728\u8fd9\u91cc",
            addContact = "添加联系人",
            joinGroup = "加入群聊",
            newGroup = "新建群聊",
            groupId = "群 ID",
            groupName = "群名称",
            groupCode = "群 ID",
            search = "搜索",
            approve = "批准",
            reject = "拒绝",
            owner = "\u521d\u59cb\u7ba1\u7406\u5458",
            member = "\u6210\u5458",
            privateMessage = "\u79c1\u4fe1",
            removeMember = "\u79fb\u9664\u6210\u5458",
            removeMemberConfirm = "\u662f\u5426\u79fb\u9664%s\uff1f",
            transferOwner = "\u8f6c\u8ba9\u521d\u59cb\u7ba1\u7406\u5458",
            transferOwnerConfirm = "\u786e\u8ba4\u5c06\u521d\u59cb\u7ba1\u7406\u5458\u8f6c\u8ba9\u7ed9%s\uff1f",
            addAdmin = "\u65b0\u589e\u7ba1\u7406\u5458",
            requestAdmin = "\u7533\u8bf7\u65b0\u589e\u7ba1\u7406\u5458",
            removeAdmin = "\u79fb\u9664\u7ba1\u7406\u5458",
            removeAdminConfirm = "\u786e\u8ba4\u5c06%s\u79fb\u9664\u7ba1\u7406\u5458\u8eab\u4efd\u5417\uff1f",
            adminRemoved = "\u5df2\u79fb\u9664\u7ba1\u7406\u5458\u8eab\u4efd",
            addGroupMember = "\u6dfb\u52a0\u7fa4\u6210\u5458",
            selectContact = "\u4ece\u597d\u53cb\u5217\u8868\u9009\u62e9",
            selectMember = "\u4ece\u7fa4\u6210\u5458\u5217\u8868\u9009\u62e9",
            noAvailableContacts = "\u6ca1\u6709\u53ef\u6dfb\u52a0\u7684\u597d\u53cb",
            noAvailableMembers = "\u6ca1\u6709\u53ef\u9009\u7684\u6210\u5458",
            memberAdded = "\u5df2\u6dfb\u52a0\u7fa4\u6210\u5458",
            adminLimit = "\u7ba1\u7406\u5458\u4e0a\u9650",
            messageExpiration = "\u6d88\u606f\u8fc7\u671f\u65f6\u95f4",
            noExpiration = "\u4e0d\u81ea\u52a8\u8fc7\u671f",
            hours8 = "8 \u5c0f\u65f6",
            hours24 = "24 \u5c0f\u65f6",
            hours72 = "72 \u5c0f\u65f6",
            incomingRequests = "待我审批",
            outgoingRequests = "等待对方审批",
            requestContact = "申请添加",
            requestJoin = "申请加入",
            contactRequestSent = "联系人申请已发送",
            joinRequestSent = "入群申请已发送",
            contactApproved = "已批准联系人申请",
            joinApproved = "已批准入群申请",
            requestRejected = "已拒绝申请",
            groupCreated = "群聊已创建",
            alreadyConnected = "已经可以单聊",
            alreadyInGroup = "已经在群聊中",
            userNotFound = "没有找到这个用户 ID",
            groupNotFound = "没有找到这个群 ID",
            invalidUserId = "请输入 8 位用户 ID",
            invalidGroupId = "请输入 10 位群 ID",
            groupNameRequired = "请输入群名称",
            incomingContactAlreadyPending = "对方已经向你发送申请，请在待审批中处理",
            notGroupAdmin = "只有群管理员可以审批",
            notContact = "\u53ea\u80fd\u6dfb\u52a0\u5df2\u7ecf\u662f\u597d\u53cb\u7684\u7528\u6237",
            requestFailed = "请求失败",
            newPassword = "\u65b0\u5bc6\u7801",
            newUsername = "\u65b0\u7528\u6237\u540d",
            usernameEmpty = "\u7528\u6237\u540d\u4e0d\u80fd\u4e3a\u7a7a",
            invalidUsername = "\u7528\u6237\u540d\u9700\u4e3a 2-24 \u4f4d\uff0c\u53ea\u80fd\u5305\u542b\u5b57\u6bcd\u3001\u6570\u5b57\u3001\u4e0b\u5212\u7ebf\u3001\u6a2a\u7ebf\u6216\u4e2d\u6587",
            usernameTaken = "\u8fd9\u4e2a\u7528\u6237\u540d\u5df2\u88ab\u5360\u7528",
            unableToChangeUsername = "\u65e0\u6cd5\u4fee\u6539\u7528\u6237\u540d",
            save = "\u4fdd\u5b58",
            replyingTo = "\u6b63\u5728\u56de\u590d",
            typeMessage = "\u8f93\u5165\u6d88\u606f",
            unreadMessages = "\u672a\u8bfb\u6d88\u606f",
            open = "\u6253\u5f00",
            downloadOpen = "\u4e0b\u8f7d / \u6253\u5f00",
            encryptedMessage = "\u52a0\u5bc6\u6d88\u606f",
            unableToDecrypt = "\u65e0\u6cd5\u89e3\u5bc6",
            encryptedAttachment = "\u52a0\u5bc6\u9644\u4ef6",
            tapOpen = "\u89e3\u5bc6\u540e\u70b9\u6253\u5f00",
            image = "\u56fe\u7247",
            voiceNote = "\u8bed\u97f3",
            file = "\u6587\u4ef6",
            language = "\u8bed\u8a00",
            displayMode = "\u663e\u793a\u6a21\u5f0f",
            followSystem = "\u8ddf\u968f\u7cfb\u7edf",
            lightMode = "\u4eae\u8272",
            darkMode = "\u6697\u8272",
            systemColors = "\u7cfb\u7edf\u914d\u8272",
            systemColorsHint = "Android 12 \u53ca\u4ee5\u4e0a\u4f1a\u4f7f\u7528\u7cfb\u7edf\u52a8\u6001\u914d\u8272",
            backAgainToExit = "\u518d\u6309\u4e00\u6b21\u8fd4\u56de\u952e\u9000\u51fa",
            logout = "\u9000\u51fa\u767b\u5f55",
            refresh = "\u5237\u65b0",
            scrollToTop = "\u56de\u5230\u9876\u90e8",
            scrollToBottom = "\u56de\u5230\u5e95\u90e8",
            admin = "\u7ba1\u7406\u5458",
            statusSeparator = " | ",
            showMenu = "\u5c55\u5f00\u83dc\u5355",
            hideMenu = "\u6536\u8d77\u83dc\u5355",
            addMedia = "\u6dfb\u52a0",
            chooseAttachment = "\u9009\u62e9\u9644\u4ef6",
            takePhoto = "\u62cd\u7167",
            startVoice = "\u5f00\u59cb\u5f55\u97f3",
            sendVoice = "\u53d1\u9001\u5f55\u97f3",
            sendMessage = "\u53d1\u9001\u6d88\u606f",
            recording = "\u5f55\u97f3\u4e2d",
            holdToTalk = "\u6309\u4f4f\u8bf4\u8bdd",
            releaseToSend = "\u677e\u5f00\u53d1\u9001",
            releaseToCancel = "\u4e0a\u6ed1\u53d6\u6d88\uff0c\u677e\u5f00\u53d6\u6d88",
            keyboardInput = "\u952e\u76d8",
            play = "\u64ad\u653e",
            pause = "\u6682\u505c",
            uploading = "\u4e0a\u4f20\u4e2d",
            downloading = "\u4e0b\u8f7d\u4e2d",
            recalledMessage = "\u5df2\u64a4\u56de\u4e00\u6761\u6d88\u606f",
            longPressRecall = "\u957f\u6309\u53ef\u64a4\u56de",
            attachmentRemoved = "\u9644\u4ef6\u5df2\u88ab\u7ba1\u7406\u5458\u6e05\u7406",
            recallAction = "\u64a4\u56de",
            currentVersion = "\u5f53\u524d\u7248\u672c",
            latestVersion = "\u670d\u52a1\u5668\u7248\u672c",
            checkUpdate = "\u68c0\u67e5\u66f4\u65b0",
            installUpdate = "\u4e0b\u8f7d\u5e76\u5b89\u88c5",
            latestVersionInstalled = "\u5df2\u662f\u6700\u65b0\u7248\u672c",
            updateAvailable = "\u53d1\u73b0\u65b0\u7248\u672c\u53ef\u7528",
            updatePromptTitle = "\u53d1\u73b0\u65b0\u7248\u672c",
            updatePromptBody = "\u68c0\u6d4b\u5230\u65b0\u7248\u672c\uff0c\u8bf7\u5c3d\u5feb\u66f4\u65b0",
            updateNow = "\u53bb\u66f4\u65b0",
            later = "\u7a0d\u540e",
            noReleaseUploaded = "\u670d\u52a1\u5668\u8fd8\u6ca1\u6709\u4e0a\u4f20\u5b89\u88c5\u5305",
            checkingUpdate = "\u68c0\u67e5\u66f4\u65b0\u4e2d",
            updateDownloaded = "\u5b89\u88c5\u5305\u5df2\u4e0b\u8f7d\uff0c\u8bf7\u7ee7\u7eed\u5b89\u88c5",
            downloadUpdate = "\u4e0b\u8f7d\u66f4\u65b0",
            openInstaller = "\u5b89\u88c5\u66f4\u65b0",
            prereleaseBuilds = "Beta \u7248",
            prereleaseCenter = "Beta \u7248\u4e0b\u8f7d",
            prereleaseAvailable = "\u670d\u52a1\u5668\u6709\u65b0\u7684 Beta \u7248",
            noPrereleaseUploaded = "\u670d\u52a1\u5668\u8fd8\u6ca1\u6709\u4e0a\u4f20 Beta APK",
            sendPhoto = "\u53d1\u9001\u7167\u7247",
            cameraPermissionDenied = "\u9700\u8981\u76f8\u673a\u6743\u9650\u624d\u80fd\u62cd\u7167",
            cameraUnavailable = "\u76f8\u673a\u6682\u65f6\u65e0\u6cd5\u6253\u5f00",
            cameraCaptureFailed = "\u62cd\u7167\u5931\u8d25",
            sendFailed = "\u53d1\u9001\u5931\u8d25",
            retrySend = "\u91cd\u65b0\u53d1\u9001",
            retrySendConfirm = "\u8981\u91cd\u65b0\u53d1\u9001\u8fd9\u6761\u6d88\u606f\u5417\uff1f",
            accessibility = AppAccessibilityStrings(
                messageStatusSent = "\u5df2\u53d1\u9001",
                messageStatusDelivered = "\u5df2\u9001\u8fbe",
                messageStatusRead = "\u5df2\u8bfb",
                expandedLabel = "\u5df2\u5c55\u5f00",
                collapsedLabel = "\u5df2\u6298\u53e0",
                selectedLabel = "\u5df2\u9009\u62e9",
            ),
            conversationPreferences = AppConversationPreferenceStrings(
                muteConversation = "\u514d\u6253\u6270",
                unmuteConversation = "\u53d6\u6d88\u514d\u6253\u6270",
                conversationMuted = "\u5df2\u5f00\u542f\u514d\u6253\u6270\uff0c\u4ecd\u4f1a\u63a5\u6536\u6d88\u606f",
                conversationUnmuted = "\u5df2\u53d6\u6d88\u514d\u6253\u6270",
                textSize = "\u5b57\u4f53\u5927\u5c0f",
                textSizeSmall = "\u5c0f",
                textSizeMedium = "\u6807\u51c6",
                textSizeLarge = "\u5927",
            ),
            deleteLocalMessage = "\u5220\u9664\u8fd9\u6761\u672c\u5730\u6d88\u606f",
            call = AppCallStrings(
                voiceCall = "\u8bed\u97f3\u901a\u8bdd",
                incomingCall = "\u6765\u7535",
                calling = "\u6b63\u5728\u62e8\u53f7",
                callConnecting = "\u8fde\u63a5\u4e2d",
                callActive = "\u901a\u8bdd\u4e2d",
                callEnded = "\u901a\u8bdd\u5df2\u7ed3\u675f",
                callRejected = "\u5bf9\u65b9\u5df2\u62d2\u7edd",
                callBusy = "\u5bf9\u65b9\u6b63\u5728\u901a\u8bdd\u4e2d",
                callUnavailable = "\u5bf9\u65b9\u6682\u65f6\u65e0\u6cd5\u63a5\u542c",
                callReconnecting = "\u7f51\u7edc\u4e0d\u4f73\uff0c\u6b63\u5728\u91cd\u8fde",
                callConnectionLost = "\u901a\u8bdd\u4fe1\u4ee4\u5df2\u65ad\u5f00",
                callFailed = "\u901a\u8bdd\u5931\u8d25",
                accept = "\u63a5\u542c",
                decline = "\u62d2\u7edd",
                endCall = "\u6302\u65ad",
                mute = "\u9759\u97f3",
                unmute = "\u53d6\u6d88\u9759\u97f3",
                audioOutput = "\u97f3\u9891\u8f93\u51fa",
                speaker = "\u514d\u63d0",
                earpiece = "\u542c\u7b52",
                bluetooth = "\u84dd\u7259\u8033\u673a",
                minimizeCall = "\u6700\u5c0f\u5316\u901a\u8bdd",
                returnToCall = "\u8fd4\u56de\u901a\u8bdd",
                overlayPermissionHint = "\u9700\u5141\u8bb8\u663e\u793a\u5728\u5176\u4ed6\u5e94\u7528\u4e0a\u65b9\uff0c\u624d\u80fd\u5728\u684c\u9762\u663e\u793a\u901a\u8bdd\u6d6e\u7a97",
                microphonePermissionDenied = "\u9700\u8981\u9ea6\u514b\u98ce\u6743\u9650\u624d\u80fd\u901a\u8bdd",
                directCallOnly = "\u53ea\u80fd\u5728\u5355\u804a\u4e2d\u53d1\u8d77\u8bed\u97f3\u901a\u8bdd",
            ),
            dates = AppDateStrings(
                today = "\u4eca\u5929",
                yesterday = "\u6628\u5929",
            ),
            maintenance = AppMaintenanceStrings(
                appVersion = "\u5e94\u7528\u7248\u672c",
                updatesSection = "\u66f4\u65b0",
                troubleshootingSection = "\u7591\u96be\u6392\u67e5",
                installUpdateAction = "\u5b89\u88c5\u66f4\u65b0",
                pushSelfTest = "\u63a8\u9001\u4e0e\u7f51\u7edc\u81ea\u68c0",
                pushSelfTestRunning = "\u6b63\u5728\u6d4b\u8bd5\u2026",
                pushSelfTestHint = "\u68c0\u67e5\u901a\u77e5\u80fd\u5426\u9001\u8fbe\u8fd9\u53f0\u8bbe\u5907",
                exportDiagnostics = "\u5bfc\u51fa\u8bca\u65ad\u65e5\u5fd7",
                exportDiagnosticsHint = "\u65e5\u5fd7\u4e0d\u5305\u542b\u6d88\u606f\u5185\u5bb9\u3001\u5bc6\u7801\u6216\u52a0\u5bc6\u5bc6\u94a5",
                profileSection = "\u4e2a\u4eba\u8d44\u6599",
                dangerZoneSection = "\u5371\u9669\u64cd\u4f5c",
                changeAvatarHint = "\u70b9\u51fb\u5934\u50cf\u5373\u53ef\u66f4\u6362",
                changePasswordHint = "\u5b9a\u671f\u66f4\u6362\u4ee5\u4fdd\u62a4\u8d26\u53f7",
                signOutHint = "\u4fdd\u7559\u8fd9\u53f0\u8bbe\u5907\u4e0a\u7684\u804a\u5929\u8bb0\u5f55",
                deleteAccountHint = "\u9700\u8981\u7ba1\u7406\u5458\u6279\u51c6\uff0c\u4e14\u65e0\u6cd5\u64a4\u9500",
                deviceStatusPending = "\u7b49\u5f85\u6279\u51c6",
                deviceStatusTrusted = "\u53ef\u4fe1\u8bbe\u5907",
                thisDeviceSection = "\u8fd9\u53f0\u8bbe\u5907",
                deleteContactConfirm = "\u5c06\u5220\u9664\u8be5\u8054\u7cfb\u4eba\u53ca\u804a\u5929\u8bb0\u5f55\uff0c\u6b64\u64cd\u4f5c\u65e0\u6cd5\u64a4\u9500\u3002",
            ),
            blog = AppBlogStrings(
                title = "\u5bb6\u5ead\u535a\u5ba2",
                chatsTab = "\u804a\u5929",
                blogTab = "\u535a\u5ba2",
                newPost = "\u53d1\u5e03\u65b0\u5e16\u5b50",
                composeHint = "\u5206\u4eab\u4e00\u4e9b\u5185\u5bb9\u2026",
                addMedia = "\u6dfb\u52a0\u56fe\u7247\u6216\u89c6\u9891",
                publish = "\u53d1\u5e03",
                publishing = "\u6b63\u5728\u53d1\u5e03",
                emptyTitle = "\u8fd8\u6ca1\u6709\u5e16\u5b50",
                emptyBody = "\u53d1\u5e03\u7b2c\u4e00\u6761\u53ea\u5bf9\u5df2\u6388\u4fe1\u8bbe\u5907\u53ef\u89c1\u7684\u5185\u5bb9\u3002",
                like = "\u70b9\u8d5e",
                unlike = "\u53d6\u6d88\u70b9\u8d5e",
                comments = "\u8bc4\u8bba",
                writeComment = "\u5199\u8bc4\u8bba\u2026",
                sendComment = "\u53d1\u9001\u8bc4\u8bba",
                deletePost = "\u5220\u9664\u5e16\u5b50",
                deletePostConfirm = "\u786e\u5b9a\u5220\u9664\u8fd9\u6761\u5e16\u5b50\u548c\u6240\u6709\u9644\u4ef6\u5417\uff1f",
                deleteComment = "\u5220\u9664\u8bc4\u8bba",
                deleteCommentConfirm = "\u786e\u5b9a\u5220\u9664\u8fd9\u6761\u8bc4\u8bba\u5417\uff1f",
                mediaLimit = "\u6700\u591a 9 \u4e2a\u5a92\u4f53\uff0c\u89c6\u9891\u6700\u591a 1 \u4e2a",
                mediaOneVideoOnly = "\u4e00\u6761\u5e16\u5b50\u53ea\u80fd\u5305\u542b 1 \u4e2a\u89c6\u9891\uff0c\u5df2\u4fdd\u7559\u7b2c\u4e00\u4e2a\u3002",
                mediaTruncated = "\u6700\u591a\u53ef\u9009 9 \u4e2a\u5a92\u4f53\uff0c\u591a\u4f59\u7684\u5df2\u5ffd\u7565\u3002",
                video = "\u89c6\u9891",
                announcement = "\u66f4\u65b0\u516c\u544a",
                loadOlder = "\u52a0\u8f7d\u66f4\u65e9\u5e16\u5b50",
                notifications = "Blog \u901a\u77e5",
                notificationsHint = "\u53ea\u5728\u4f60\u7684\u5e16\u5b50\u6536\u5230\u65b0\u8bc4\u8bba\u65f6\u901a\u77e5",
            ),
        )

        AppLanguage.EN -> AppStrings(
            familyChat = "Family Chat",
            appSubtitle = "Android client for encrypted family messaging.",
            serverUrl = "Server URL",
            username = "Username",
            password = "Password",
            login = "Login",
            register = "Register",
            createAccount = "Request account",
            backToLogin = "Back to login",
            confirmPassword = "Confirm password",
            registrationPending = "Registration request submitted. Please wait for admin approval.",
            passwordTooShort = "Password must be at least 8 characters",
            passwordsDoNotMatch = "Passwords do not match",
            requestAlreadyPending = "A request for this username is already pending",
            unableToRegister = "Unable to submit registration request",
            connected = "Connected",
            disconnected = "Disconnected",
            reconnecting = "Reconnecting",
            syncing = "Syncing",
            e2ee = "E2EE",
            settings = "Settings",
            general = "General",
            about = "About",
            security = "Security",
            accountManage = "Account",
            friendManage = "Contact",
            groupManage = "Group management",
            deleteHistory = "Delete history",
            clearChatHistory = "Clear this chat history",
            deleteHistoryConfirm = "Delete all messages for everyone?",
            deleteDirectChat = "Delete direct chat",
            deleteDirectChatConfirm = "Delete this direct chat? Messages and attachments in this chat will be deleted, and the other side will lose this chat too.",
            deleteContact = "Delete contact",
            deleteGroup = "Delete group",
            deleteGroupConfirm = "Delete this group? All members will lose access to this group.",
            leaveGroup = "Leave group",
            leaveGroupConfirm = "Leave this group? No admin approval is required.",
            requestAccountDeletion = "Request account deletion",
            requestAccountDeletionConfirm = "Submit an account deletion request? After admin approval, this account will no longer be able to log in.",
            accountDeletionRequested = "Account deletion request submitted. Please wait for admin approval.",
            conversationDeleted = "Direct chat deleted",
            groupDeleted = "Group deleted",
            groupLeft = "Left group",
            unableToDeleteConversation = "Unable to delete this direct chat",
            unableToDeleteGroup = "Unable to delete this group",
            unableToLeaveGroup = "Unable to leave group",
            ownerCannotLeaveGroup = "The initial admin cannot leave directly. Transfer the initial admin role first or delete the group.",
            ownerTransferred = "Initial admin transferred",
            delete = "Delete",
            cancel = "Cancel",
            changePassword = "Change password",
            changeUsername = "Change username",
            changeAvatar = "Change avatar",
            changeGroupIcon = "Change group icon",
            avatarHint = "Upload a new avatar",
            avatarCropHint = "Drag and zoom the image to adjust the circular crop area.",
            userId = "ID",
            deviceSecurity = "Device security",
            safetyCode = "Safety code",
            deviceId = "Device ID",
            deviceName = "Device name",
            safetyCodeHint = "This code comes from this device's identity public key. It changes after reinstalling the app or changing phones.",
            noDeviceIdentity = "Device identity has not been generated yet",
            devices = "Signed-in devices",
            currentDevice = "Current device",
            lastSeen = "Last seen",
            removeDevice = "Remove device",
            removeDeviceConfirm = "Remove device %s? It will no longer receive new group chat keys.",
            deviceAdded = "A new device was added. Verify the safety code.",
            deviceRemoved = "A device was removed. Group chat keys were rotated.",
            groupKeyStatus = "Group key status",
            groupKeyEpoch = "Key epoch",
            groupKeyDevicesReady = "Covered devices",
            peerSafetyCode = "Peer safety code",
            safetyCodeChanged = "Safety code changed. Verify the identity with this contact.",
            noPeerSafetyCode = "The other side has not uploaded a device safety code yet",
            contactsAndGroups = "Contacts and groups",
            shareToChat = "Share to chat",
            shareLoginFirst = "Log in first to share",
            sharedContentUnsupported = "This shared content is not supported yet",
            noChatsTitle = "No chats yet",
            noChatsBody = "Add a contact or join a group to start chatting.",
            addContact = "Add contact",
            joinGroup = "Join group",
            newGroup = "New group",
            groupId = "Group ID",
            groupName = "Group name",
            groupCode = "Group ID",
            search = "Search",
            approve = "Approve",
            reject = "Reject",
            owner = "Initial admin",
            member = "Member",
            privateMessage = "Message",
            removeMember = "Remove member",
            removeMemberConfirm = "Remove %s from this group?",
            transferOwner = "Transfer initial admin",
            transferOwnerConfirm = "Transfer the initial admin role to %s?",
            addAdmin = "Add admin",
            requestAdmin = "Request admin",
            removeAdmin = "Remove admin",
            removeAdminConfirm = "Remove %s as an admin?",
            adminRemoved = "Admin role removed",
            addGroupMember = "Add group member",
            selectContact = "Select from contacts",
            selectMember = "Select from members",
            noAvailableContacts = "No available contacts",
            noAvailableMembers = "No available members",
            memberAdded = "Group member added",
            adminLimit = "Admin limit",
            messageExpiration = "Message expiration",
            noExpiration = "No auto expiration",
            hours8 = "8 hours",
            hours24 = "24 hours",
            hours72 = "72 hours",
            incomingRequests = "Needs my approval",
            outgoingRequests = "Waiting for approval",
            requestContact = "Request contact",
            requestJoin = "Request join",
            contactRequestSent = "Contact request sent",
            joinRequestSent = "Join request sent",
            contactApproved = "Contact request approved",
            joinApproved = "Join request approved",
            requestRejected = "Request rejected",
            groupCreated = "Group created",
            alreadyConnected = "You can already chat",
            alreadyInGroup = "You are already in this group",
            userNotFound = "User ID not found",
            groupNotFound = "Group ID not found",
            invalidUserId = "Enter an 8-digit user ID",
            invalidGroupId = "Enter a 10-digit group ID",
            groupNameRequired = "Enter a group name",
            incomingContactAlreadyPending = "They already sent you a request. Review it in pending approvals.",
            notGroupAdmin = "Only group admins can approve this",
            notContact = "Only existing contacts can be added",
            requestFailed = "Request failed",
            newPassword = "New password",
            newUsername = "New username",
            usernameEmpty = "Username cannot be empty",
            invalidUsername = "Username must be 2-24 characters and use letters, numbers, underscores, hyphens, or Chinese characters",
            usernameTaken = "That username is already taken",
            unableToChangeUsername = "Unable to change username",
            save = "Save",
            replyingTo = "Replying to",
            typeMessage = "Type a message",
            unreadMessages = "Unread messages",
            open = "Open",
            downloadOpen = "Download / Open",
            encryptedMessage = "Encrypted message",
            unableToDecrypt = "Unable to decrypt",
            encryptedAttachment = "Encrypted attachment",
            tapOpen = "Tap open after decrypt",
            image = "Image",
            voiceNote = "Voice note",
            file = "File",
            language = "Language",
            displayMode = "Display mode",
            followSystem = "Follow system",
            lightMode = "Light",
            darkMode = "Dark",
            systemColors = "System colors",
            systemColorsHint = "On Android 12+, use the system dynamic color palette",
            backAgainToExit = "Press back again to exit",
            logout = "Logout",
            refresh = "Refresh",
            scrollToTop = "Scroll to top",
            scrollToBottom = "Scroll to bottom",
            admin = "admin",
            statusSeparator = " | ",
            showMenu = "Show menu",
            hideMenu = "Hide menu",
            addMedia = "Add",
            chooseAttachment = "Choose attachment",
            takePhoto = "Take photo",
            startVoice = "Start voice",
            sendVoice = "Send voice",
            sendMessage = "Send message",
            recording = "Recording",
            holdToTalk = "Hold to talk",
            releaseToSend = "Release to send",
            releaseToCancel = "Slide up to cancel",
            keyboardInput = "Keyboard",
            play = "Play",
            pause = "Pause",
            uploading = "Uploading",
            downloading = "Downloading",
            recalledMessage = "Message recalled",
            longPressRecall = "Long press to recall",
            attachmentRemoved = "Attachment removed by admin",
            recallAction = "Recall",
            currentVersion = "Current version",
            latestVersion = "Server version",
            checkUpdate = "Check update",
            installUpdate = "Download and install",
            latestVersionInstalled = "You already have the latest version",
            updateAvailable = "A newer version is available",
            updatePromptTitle = "Update available",
            updatePromptBody = "A new version was detected. Please update as soon as possible.",
            updateNow = "Update now",
            later = "Later",
            noReleaseUploaded = "No release APK has been uploaded yet",
            checkingUpdate = "Checking for updates",
            updateDownloaded = "Update downloaded. Continue to install",
            downloadUpdate = "Download update",
            openInstaller = "Install update",
            prereleaseBuilds = "Beta",
            prereleaseCenter = "Beta downloads",
            prereleaseAvailable = "A new beta build is on the server",
            noPrereleaseUploaded = "No beta APK has been uploaded yet",
            sendPhoto = "Send photo",
            cameraPermissionDenied = "Camera permission is required",
            cameraUnavailable = "Camera is currently unavailable",
            cameraCaptureFailed = "Unable to capture photo",
            sendFailed = "Send failed",
            retrySend = "Retry send",
            retrySendConfirm = "Retry sending this message?",
            accessibility = AppAccessibilityStrings(
                messageStatusSent = "Sent",
                messageStatusDelivered = "Delivered",
                messageStatusRead = "Read",
                expandedLabel = "Expanded",
                collapsedLabel = "Collapsed",
                selectedLabel = "Selected",
            ),
            conversationPreferences = AppConversationPreferenceStrings(
                muteConversation = "Mute notifications",
                unmuteConversation = "Unmute notifications",
                conversationMuted = "Muted. Messages still arrive.",
                conversationUnmuted = "Notifications on",
                textSize = "Text size",
                textSizeSmall = "Small",
                textSizeMedium = "Standard",
                textSizeLarge = "Large",
            ),
            deleteLocalMessage = "Delete this local message",
            call = AppCallStrings(
                voiceCall = "Voice call",
                incomingCall = "Incoming call",
                calling = "Calling",
                callConnecting = "Connecting",
                callActive = "In call",
                callEnded = "Call ended",
                callRejected = "Call rejected",
                callBusy = "The other side is busy",
                callUnavailable = "The other side is unavailable",
                callReconnecting = "Poor network, trying to reconnect",
                callConnectionLost = "Call signaling disconnected",
                callFailed = "Call failed",
                accept = "Accept",
                decline = "Decline",
                endCall = "End call",
                mute = "Mute",
                unmute = "Unmute",
                audioOutput = "Audio output",
                speaker = "Speaker",
                earpiece = "Earpiece",
                bluetooth = "Bluetooth",
                minimizeCall = "Minimize call",
                returnToCall = "Return to call",
                overlayPermissionHint = "Allow display over other apps to show the floating call bubble on the desktop",
                microphonePermissionDenied = "Microphone permission is required for calls",
                directCallOnly = "Voice calls are only available in direct chats",
            ),
            dates = AppDateStrings(
                today = "Today",
                yesterday = "Yesterday",
            ),
            maintenance = AppMaintenanceStrings(
                appVersion = "App version",
                updatesSection = "Updates",
                troubleshootingSection = "Troubleshooting",
                installUpdateAction = "Install update",
                pushSelfTest = "Push and network self-test",
                pushSelfTestRunning = "Testing…",
                pushSelfTestHint = "Check whether notifications reach this device",
                exportDiagnostics = "Export diagnostics",
                exportDiagnosticsHint = "Logs exclude message content, passwords, and encryption keys",
                profileSection = "Profile",
                dangerZoneSection = "Danger zone",
                changeAvatarHint = "Tap your photo to change it",
                changePasswordHint = "Change it periodically to keep the account safe",
                signOutHint = "Keeps this device's chat history",
                deleteAccountHint = "Needs admin approval and cannot be undone",
                deviceStatusPending = "Pending approval",
                deviceStatusTrusted = "Trusted",
                thisDeviceSection = "This device",
                deleteContactConfirm = "This removes the contact and your chat history with them. It cannot be undone.",
            ),
            blog = AppBlogStrings(
                title = "Family Blog",
                chatsTab = "Chats",
                blogTab = "Blog",
                newPost = "New post",
                composeHint = "Share something…",
                addMedia = "Add images or video",
                publish = "Publish",
                publishing = "Publishing",
                emptyTitle = "No posts yet",
                emptyBody = "Publish the first post visible only to trusted Family Chat devices.",
                like = "Like",
                unlike = "Unlike",
                comments = "Comments",
                writeComment = "Write a comment…",
                sendComment = "Send comment",
                deletePost = "Delete post",
                deletePostConfirm = "Delete this post and all of its media?",
                deleteComment = "Delete comment",
                deleteCommentConfirm = "Delete this comment?",
                mediaLimit = "Up to 9 media items and one video",
                mediaOneVideoOnly = "A post can hold one video. The first one was kept.",
                mediaTruncated = "Up to 9 items can be attached. The extras were left out.",
                video = "Video",
                announcement = "Announcement",
                loadOlder = "Load older posts",
                notifications = "Blog notifications",
                notificationsHint = "Notify only when your posts receive new comments",
            ),
        )
    }
