package com.example.chat

data class ChatUiState(
    val serverUrl: String = DEFAULT_SERVER_URL,
    val e2eeEnabled: Boolean = true,
    val language: AppLanguage = AppLanguage.systemDefault(),
    val displayMode: AppDisplayMode = AppDisplayMode.SYSTEM,
    val dynamicColorsEnabled: Boolean = true,
    val textSize: AppTextSize = AppTextSize.MEDIUM,
    val isLoading: Boolean = false,
    val isLoggedIn: Boolean = false,
    val isConnected: Boolean = false,
    val connectionStatus: ConnectionStatus = ConnectionStatus.OFFLINE,
    val me: ChatUser? = null,
    val deviceIdentity: DeviceIdentityInfo? = null,
    val deviceIdentities: List<DevicePublicIdentity> = emptyList(),
    val myDevices: List<DevicePublicIdentity> = emptyList(),
    val users: List<ChatUser> = emptyList(),
    val conversations: List<ConversationSummary> = emptyList(),
    val contactRequests: List<ContactRequestInfo> = emptyList(),
    val groupJoinRequests: List<GroupJoinRequestInfo> = emptyList(),
    val userLookupResult: UserLookupResult? = null,
    val groupLookupResult: GroupLookupResult? = null,
    val currentConversationManage: ConversationManageInfo? = null,
    val relationshipMessage: String? = null,
    val currentConversationId: Long = 0L,
    val currentConversationDeliveryStates: Map<String, Long> = emptyMap(),
    val currentConversationReadStates: Map<String, Long> = emptyMap(),
    val messages: List<ChatMessage> = emptyList(),
    val isRefreshing: Boolean = false,
    val uploadProgress: TransferProgress? = null,
    val downloadProgress: TransferProgress? = null,
    val latestAppRelease: AppReleaseInfo? = null,
    val downloadedUpdate: DecryptedAttachment? = null,
    val isCheckingUpdate: Boolean = false,
    val updateStatus: String? = null,
    val latestPrerelease: AppReleaseInfo? = null,
    val downloadedPrerelease: DecryptedAttachment? = null,
    val isCheckingPrerelease: Boolean = false,
    val prereleaseStatus: String? = null,
    val registrationMessage: String? = null,
    val registrationUserCode: String = "",
    val deviceApprovalPending: Boolean = false,
    val pendingDeviceId: String = "",
    val voiceCall: VoiceCallUiState = VoiceCallUiState(),
    val error: String? = null,
)

enum class ConnectionStatus {
    OFFLINE,
    CONNECTED,
    SYNCING,
    RECONNECTING,
}
